micronaut:
  server:
    port: 8080
  application:
    name: book-micronaut-reactive
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

endpoints:
  prometheus:
    sensitive: false

r2dbc:
  datasources:
    default:
      schema-generate: none
      dialect: MYSQL
      url: r2dbc:mysql://book-mysql-db:3306/performance-books
      username: root
      password: root

netty:
  default:
    allocator:
      max-order: 3

vertx:
  mysql:
    client:
      port: 3306
      host: book-mysql-db
      database: performance-books
      user: root
      password: root
      maxSize: 5

jackson:
  dateFormat: yyyy-MM-dd
  timeZone: UTC
  serialization:
    writeDatesAsTimestamps: false


