version: '3.7'
services:

  metabase-mysql-db:
    restart: always
    container_name: metabase-mysql-db
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./database/dashboard_schema.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_ROOT_USERNAME --password=$$MYSQL_ROOT_PASSWORD
      timeout: 2s
      retries: 2

  metabase:
    image: metabase/metabase
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_DBNAME: "performance-dashboard"
      MB_DB_PORT: "3306"
      MB_DB_USER: "root"
      MB_DB_PASS: "root"
      MB_DB_HOST: "metabase-mysql-db"
      MB_DB_TYPE: "mysql"
    depends_on:
      metabase-mysql-db:
        condition: service_healthy