version: '3.7'
services:

  book-mysql-db:
    restart: always
    container_name: book-mysql-db
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ../book-database/src/main/resources/scripts/book_schema.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_ROOT_USERNAME --password=$$MYSQL_ROOT_PASSWORD
      timeout: 2s
      retries: 2

  ms-book-dotnet-entityframework:
    image: pt-book/ms-book-dotnet-entity-framework
    container_name: ms-book-dotnet-entity-framework
    build:
      context: ../ms-book-dotnet-entity-framework
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      book-mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - PROFILE=docker